services:
  dash:
    build:
      context: ./kindledash
    ports:
      - "8001:8080"
  screenshot-server:
    build:
      context: ./screenshot-server
    ports:
      - "8000:8000"
    environment:
      - IMAGE_PATH=/app/image_drop/image.png
    volumes:
      - image_drop:/app/image_drop
  screenshot-taker:
    build:
      context: ./screenshot-taker
    environment:
      - OUTPUT_PATH=/app/image_drop/image.png
      - UPDATE_SECONDS=60
      - URL=http://dash:8080
      - IMG_WIDTH=1072
      - IMG_HEIGHT=1448
    volumes:
      - image_drop:/app/image_drop
volumes:
  image_drop:
